/**
 * Phase 3 units: the source registry, selector overrides, the session log,
 * the mapping status screen, and the pre-fill data quality gate.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { beforeEach, describe, expect, it } from 'vitest';
import * as XLSX from 'xlsx';

import { readWorkbookBytes } from '../src/excel/excelReader.js';
import { TEMPLATE_COLUMNS } from '../src/excel/columnAliases.js';
import { validateShipment } from '../src/excel/validator.js';
import { ExcelSource } from '../src/sources/ExcelSource.js';
import { QuickBooksExportSource } from '../src/sources/QuickBooksExportSource.js';
import { WebSource } from '../src/sources/WebSource.js';
import { loadWorkbook, sourceForWorkbook, WORKBOOK_SOURCES } from '../src/sources/index.js';
import { DEFAULT_SETTINGS } from '../src/core/settings.js';
import {
  applyOverrides,
  emptyOverrides,
  OverrideError,
  parseOverrides,
  serializeOverrides,
  starterOverrides,
  unknownOverrideKeys,
} from '../src/ace/selectors/overrides.js';
import { ALL_MAPPINGS, fieldsForPage, resolveFields } from '../src/ace/mappings/index.js';
import { detectField } from '../src/content/fieldDetector.js';
import { fillFields } from '../src/content/filler.js';
import {
  appendEntry,
  formatLog,
  looksLikeSecret,
  makeEntry,
  MAX_LOG_ENTRIES,
  type SessionLogEntry,
} from '../src/core/sessionLog.js';
import {
  applyFillReport,
  buildMappingStatus,
  formatMappingStatus,
  summarizeMappingStatus,
} from '../src/ui/mappingStatus.js';
import { buildPreflight, summarizePreflight } from '../src/ui/preflight.js';
import { isKnownUom } from '../src/ace/transformers/codes.js';

// ---------------------------------------------------------------- fixtures

const ROW: Array<string | number> = [
  1, 'OS', '0802.12.0000', 'SHELLED ALMONDS', 79832, 'KG', '', '', 'D', 651217.6, 176000, 'lb', 'EAR99', 'C33',
  'Aydin Kuruyemis San Ve Tic A.S', 'CN-1042', '2026-09-21', 'Organize Sanayi Bolgesi 3. Cadde No 14', '', 'Aydin', '', '09100', 'TR', 'CA', 'CIF', 'NET 120', '2027-01-19',
  '3993', 'MSCU', 'MSC FIRENZE V.541W', 'EBKG18531408', 'MSCU1234567', 'SL-4471209', 'TR',
];

function workbookBytes(extraSheets: Array<{ name: string; rows: Array<Array<string | number>> }> = []): Uint8Array {
  const book = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(book, XLSX.utils.aoa_to_sheet([TEMPLATE_COLUMNS, ROW]), 'Shipment');
  for (const sheet of extraSheets) {
    XLSX.utils.book_append_sheet(book, XLSX.utils.aoa_to_sheet(sheet.rows), sheet.name);
  }
  return new Uint8Array(XLSX.write(book, { type: 'array', bookType: 'xlsx' }) as ArrayBuffer);
}

const AUDIT_ROWS: Array<Array<string | number>> = [
  ['ACE Helper - QuickBooks export audit', ''],
  ['Source', 'QuickBooks invoice CN-1042'],
  ['Exported', '2026-09-21T09:31:44.000Z'],
  ['Generated by', 'QuickBooks Desktop (qbXML 16.0) via saved responses'],
];

function html(name: string): string {
  return readFileSync(join(__dirname, 'fixtures', `${name}.html`), 'utf8');
}

// ------------------------------------------------------------ source seam

describe('the invoice data source seam', () => {
  it('falls back to ExcelSource for a plain workbook', () => {
    const workbook = readWorkbookBytes(workbookBytes(), 'hand-filled.xlsx');
    expect(sourceForWorkbook(workbook).id).toBe('excel');
  });

  it('recognises a companion-written workbook by its Audit sheet', () => {
    const workbook = readWorkbookBytes(workbookBytes([{ name: 'Audit', rows: AUDIT_ROWS }]), 'ACE_Invoice_CN-1042.xlsx');
    const source = sourceForWorkbook(workbook);
    expect(source.id).toBe('quickbooks-export');
    expect(source.describe(workbook).detail).toContain('qbXML 16.0');
    expect(source.describe(workbook).detail).toContain('exported 2026-09-21');
  });

  it('does not claim a workbook that merely has a sheet called Audit', () => {
    const bytes = workbookBytes([{ name: 'Audit', rows: [['My own notes', '']] }]);
    const workbook = readWorkbookBytes(bytes, 'notes.xlsx');
    expect(new QuickBooksExportSource().accepts(workbook)).toBe(0);
    expect(sourceForWorkbook(workbook).id).toBe('excel');
  });

  it('parses identically whichever source claims the file', () => {
    const workbook = readWorkbookBytes(workbookBytes([{ name: 'Audit', rows: AUDIT_ROWS }]), 'ACE_Invoice_CN-1042.xlsx');
    const viaExcel = new ExcelSource().load(workbook, { settings: DEFAULT_SETTINGS });
    const viaQb = new QuickBooksExportSource().load(workbook, { settings: DEFAULT_SETTINGS });

    expect(viaQb.shipment.invoice).toEqual(viaExcel.shipment.invoice);
    expect(viaQb.shipment.commodities).toEqual(viaExcel.shipment.commodities);
    expect(viaQb.shipment.provenance).toEqual(viaExcel.shipment.provenance);
    expect(viaQb.validation).toEqual(viaExcel.validation);
    // Only the label differs.
    expect(viaQb.source.id).not.toBe(viaExcel.source.id);
  });

  it('always has a source that will take a readable workbook', () => {
    const workbook = readWorkbookBytes(workbookBytes(), 'anything.xlsx');
    expect(WORKBOOK_SOURCES.some((source) => source.accepts(workbook) > 0)).toBe(true);
    expect(loadWorkbook(workbook, { settings: DEFAULT_SETTINGS }).shipment.commodities).toHaveLength(1);
  });

  it('declares the web source unavailable rather than half-implemented', () => {
    const web = new WebSource();
    expect(web.available).toBe(false);
    expect(() => web.load(undefined as never, { settings: DEFAULT_SETTINGS })).toThrow(/not built/);
  });
});

// --------------------------------------------------------- selector config

describe('selector overrides', () => {
  it('is empty by default and changes nothing', () => {
    expect(applyOverrides(fieldsForPage('commodities'), emptyOverrides())).toEqual(fieldsForPage('commodities'));
    expect(resolveFields('commodities', 'commodityLine', null)).toEqual(fieldsForPage('commodities', 'commodityLine'));
  });

  it('puts a captured selector ahead of the built-in candidates', () => {
    const overrides = parseOverrides({
      version: 1,
      capturedAt: '2026-09-24',
      fields: { ScheduleB: [{ strategy: 'id', selector: '#filingForm_scheduleB' }] },
    });
    const mapped = applyOverrides(fieldsForPage('commodities'), overrides);
    const scheduleB = mapped.find((field) => field.key === 'ScheduleB');

    expect(scheduleB?.candidates[0]).toMatchObject({ strategy: 'id', selector: '#filingForm_scheduleB', verified: true });
    expect(scheduleB?.verificationStatus).toBe('verified');
    // The built-ins stay behind it, so a wrong paste degrades to today.
    expect(scheduleB?.candidates.length).toBeGreaterThan(1);
  });

  it('actually resolves a field through a captured selector', () => {
    document.body.innerHTML =
      '<div data-section="commodityLine"><input id="filingForm_scheduleB" type="text" aria-label="whatever" /></div>';
    const overrides = parseOverrides({
      fields: { ScheduleB: [{ strategy: 'id', selector: '#filingForm_scheduleB' }] },
    });
    const field = applyOverrides(fieldsForPage('commodities'), overrides).find((item) => item.key === 'ScheduleB');
    const detection = detectField(field!, { root: document });

    expect(detection.status).toBe('FOUND');
    expect(detection.confidence).toBe('high');
    expect((detection.element as HTMLInputElement).id).toBe('filingForm_scheduleB');
  });

  it('refuses malformed input rather than half-applying it', () => {
    expect(() => parseOverrides('not json')).toThrow(OverrideError);
    expect(() => parseOverrides({ version: 99, fields: {} })).toThrow(/Unsupported override version/);
    expect(() => parseOverrides({ fields: { ScheduleB: 'nope' } })).toThrow(/must be an array/);
    expect(() => parseOverrides({ fields: { ScheduleB: [{ strategy: 'psychic', selector: '#x' }] } })).toThrow(/strategy must be one of/);
    expect(() => parseOverrides({ fields: { ScheduleB: [{ strategy: 'id' }] } })).toThrow(/must be a string/);
    expect(() => parseOverrides({ fields: { 'not a key': [{ strategy: 'id', selector: '#x' }] } })).toThrow(/not a valid ACE field key/);
  });

  it('rejects a selector the browser cannot parse, at paste time', () => {
    expect(() => parseOverrides({ fields: { ScheduleB: [{ strategy: 'id', selector: '#[[[' }] } }, document)).toThrow(
      /not a valid CSS selector/,
    );
  });

  it('drops __proto__ instead of polluting anything', () => {
    const parsed = parseOverrides(JSON.parse('{"fields":{"__proto__":[{"strategy":"id","selector":"#x"}]}}'));
    expect(Object.keys(parsed.fields)).toEqual([]);
    expect(({} as Record<string, unknown>)['strategy']).toBeUndefined();
  });

  it('names override keys that match no ACE field', () => {
    const overrides = parseOverrides({ fields: { NotAField: [{ strategy: 'id', selector: '#x' }] } });
    expect(unknownOverrideKeys(ALL_MAPPINGS, overrides)).toEqual(['NotAField']);
  });

  it('writes a starter file for the fields that did not resolve', () => {
    const starter = starterOverrides(ALL_MAPPINGS, ['ScheduleB', 'ShippingWeight']);
    expect(Object.keys(starter.fields)).toEqual(['ScheduleB', 'ShippingWeight']);
    expect(serializeOverrides(starter)).toContain('REPLACE_WITH_THE_ID_FROM_ACE_FOR_ScheduleB');
    // And it round-trips through the parser, apart from the placeholder text.
    expect(() => parseOverrides(serializeOverrides(starter))).not.toThrow();
  });

  it('keeps selectors out of the mapping files', () => {
    // The separation is the point: a mapping says what to fill, a selector
    // table says where. A regression here means they merged again.
    const mapping = readFileSync(join(__dirname, '..', 'src', 'ace', 'mappings', 'commodities.ts'), 'utf8');
    expect(mapping).not.toMatch(/#[a-z][A-Za-z]*'/);
    expect(mapping).toContain('COMMODITY_SELECTORS');
  });
});

// ------------------------------------------------------------- session log

describe('the session log', () => {
  it('records what happened, with a clock time', () => {
    const entry = makeEntry('transform', 'Line 1 ShippingWeight: 176000 lb -> 79832 kg', 'lb x 0.45359237');
    expect(entry?.kind).toBe('transform');
    expect(entry?.detail).toBe('lb x 0.45359237');
    expect(formatLog([entry as SessionLogEntry])).toMatch(/\d{2}:\d{2}:\d{2}\s+transform/);
  });

  it('refuses anything that looks like a credential', () => {
    expect(looksLikeSecret('the password is hunter2')).toBe(true);
    expect(looksLikeSecret('Authorization: Bearer abcdefghijk')).toBe(true);
    expect(looksLikeSecret('Line 1 weight 176000 lb')).toBe(false);

    const refused = makeEntry('note', 'ACE password is hunter2');
    expect(refused?.kind).toBe('note');
    expect(refused?.message).toContain('refused');
    expect(refused?.message).not.toContain('hunter2');
  });

  it('keeps the most recent entries and drops the oldest', () => {
    let log: SessionLogEntry[] = [];
    for (let index = 0; index < MAX_LOG_ENTRIES + 25; index += 1) {
      log = appendEntry(log, makeEntry('note', `entry ${index}`));
    }
    expect(log).toHaveLength(MAX_LOG_ENTRIES);
    expect(log[0]?.message).toBe('entry 25');
    expect(log[log.length - 1]?.message).toBe(`entry ${MAX_LOG_ENTRIES + 24}`);
  });

  it('says so plainly when nothing has happened', () => {
    expect(formatLog([], 'Invoice CN-1042')).toContain('no activity recorded');
    expect(formatLog([], 'Invoice CN-1042')).toContain('uploaded');
  });
});

// --------------------------------------------------------- mapping status

describe('the mapping status screen', () => {
  const workbook = readWorkbookBytes(workbookBytes([{ name: 'Audit', rows: AUDIT_ROWS }]), 'ACE_Invoice_CN-1042.xlsx');
  const loaded = loadWorkbook(workbook, { settings: DEFAULT_SETTINGS });

  it('answers all six questions for every mapped field', () => {
    const rows = buildMappingStatus(loaded.shipment, { settings: DEFAULT_SETTINGS, line: 1, source: loaded.source });
    expect(rows).toHaveLength(ALL_MAPPINGS.length);

    const weight = rows.find((row) => row.key === 'ShippingWeight');
    expect(weight?.source).toContain('QuickBooks export');
    expect(weight?.original).toContain('176000');
    expect(weight?.transform).toContain('0.45359237');
    expect(weight?.aceValue).toBe('79832');
    expect(weight?.aceField).toBe('Shipping Weight (whole Kilograms)');
    // The real ACE path is `shipmentWeight`, captured 2026-09-16; the old
    // guess `shippingWeight` only ever matched the visible label.
    expect(weight?.selector).toContain('shipmentWeight');
  });

  it('works with no ACE page open, and says the page was not checked', () => {
    const rows = buildMappingStatus(loaded.shipment, { settings: DEFAULT_SETTINGS, line: 1 });
    expect(rows.find((row) => row.key === 'ScheduleB')?.status).toBe('NOT CHECKED');
  });

  it('marks a field ACE expects but the data does not carry as MISSING', () => {
    const thin = structuredClone(loaded.shipment);
    thin.commodities[0]!.licenseCode = '';
    const rows = buildMappingStatus(thin, { settings: DEFAULT_SETTINGS, line: 1 });
    expect(rows.find((row) => row.key === 'LicenseCode')?.status).toBe('MISSING');
    // An optional field with no value is EMPTY, not MISSING: the two are
    // different problems and must not read alike.
    expect(rows.find((row) => row.key === 'Quantity2')?.status).toBe('EMPTY');
  });

  it('upgrades to READY once a dry run finds the field on the page', () => {
    document.body.innerHTML = html('ace-commodities');
    const rows = buildMappingStatus(loaded.shipment, { settings: DEFAULT_SETTINGS, line: 1, source: loaded.source });
    const report = fillFields(
      { shipment: loaded.shipment, page: 'commodities', scope: 'commodityLine', line: 1, settings: DEFAULT_SETTINGS, dryRun: true },
      document,
    );

    const resolved = applyFillReport(rows, report);
    expect(resolved.find((row) => row.key === 'ScheduleB')?.status).toBe('READY');
    // A dry run writes nothing.
    expect((document.getElementById('scheduleBNumber') as HTMLInputElement).value).toBe('');
  });

  it('says NOT FOUND when the field is not on the page', () => {
    document.body.innerHTML = html('ace-commodities');
    document.getElementById('licenseCode')?.remove();
    const rows = buildMappingStatus(loaded.shipment, { settings: DEFAULT_SETTINGS, line: 1 });
    const report = fillFields(
      { shipment: loaded.shipment, page: 'commodities', scope: 'commodityLine', line: 1, settings: DEFAULT_SETTINGS, dryRun: true },
      document,
    );
    expect(applyFillReport(rows, report).find((row) => row.key === 'LicenseCode')?.status).toBe('NOT FOUND');
  });

  it('renders as an aligned text table for the clipboard', () => {
    const rows = buildMappingStatus(loaded.shipment, { settings: DEFAULT_SETTINGS, line: 1, source: loaded.source });
    const text = formatMappingStatus(rows);
    expect(text.split('\n')[0]).toMatch(/Field\s+Source\s+Original\s+Transformation\s+ACE value\s+ACE field\s+Selector\s+Status/);
    expect(summarizeMappingStatus(rows).total).toBe(ALL_MAPPINGS.length);
  });
});

// ------------------------------------------------------- data quality gate

describe('the pre-fill data quality gate', () => {
  const clean = loadWorkbook(readWorkbookBytes(workbookBytes(), 'clean.xlsx'), { settings: DEFAULT_SETTINGS });

  function damaged(mutate: (row: Array<string | number>) => void) {
    const row = [...ROW];
    mutate(row);
    const book = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(book, XLSX.utils.aoa_to_sheet([TEMPLATE_COLUMNS, row]), 'Shipment');
    const bytes = new Uint8Array(XLSX.write(book, { type: 'array', bookType: 'xlsx' }) as ArrayBuffer);
    return loadWorkbook(readWorkbookBytes(bytes, 'damaged.xlsx'), { settings: DEFAULT_SETTINGS });
  }

  function statusOf(loaded: ReturnType<typeof loadWorkbook>, id: string): string | undefined {
    return buildPreflight(loaded.shipment, loaded.validation, loaded.notes).checks.find((check) => check.id === id)?.status;
  }

  it('passes a clean sheet', () => {
    const result = buildPreflight(clean.shipment, clean.validation, clean.notes);
    expect(result.ready).toBe(true);
    expect(result.blocking).toEqual([]);
    expect(summarizePreflight(result)).toContain('passed');
  });

  it('fails a missing Schedule B', () => {
    expect(statusOf(damaged((row) => (row[2] = '')), 'scheduleB')).toBe('fail');
  });

  it('warns on a missing origin', () => {
    expect(statusOf(damaged((row) => (row[8] = '')), 'origin')).toBe('warn');
  });

  it('warns on a missing licence code', () => {
    expect(statusOf(damaged((row) => (row[13] = '')), 'licence')).toBe('warn');
  });

  it('fails a negative amount', () => {
    const loaded = damaged((row) => (row[9] = -100));
    expect(statusOf(loaded, 'amounts')).toBe('fail');
    expect(buildPreflight(loaded.shipment, loaded.validation, loaded.notes).blocking[0]?.message).toContain('no negative value');
  });

  it('warns on a zero weight and fails a negative one', () => {
    expect(statusOf(damaged((row) => (row[10] = 0)), 'weights')).toBe('warn');
    expect(statusOf(damaged((row) => (row[10] = -5)), 'weights')).toBe('fail');
  });

  it('fails an invalid date', () => {
    expect(statusOf(damaged((row) => (row[16] = 'the third of never')), 'dates')).toBe('fail');
  });

  it('warns on a unit of measure ACE does not use', () => {
    expect(isKnownUom('KG')).toBe(true);
    expect(isKnownUom('BUSHELS')).toBe(false);
    expect(statusOf(damaged((row) => (row[5] = 'BUSHELS')), 'uom')).toBe('warn');
  });

  it('warns about a column nobody mapped', () => {
    const book = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(
      book,
      XLSX.utils.aoa_to_sheet([[...TEMPLATE_COLUMNS, 'BrokerReference'], [...ROW, 'PCB-991']]),
      'Shipment',
    );
    const bytes = new Uint8Array(XLSX.write(book, { type: 'array', bookType: 'xlsx' }) as ArrayBuffer);
    const loaded = loadWorkbook(readWorkbookBytes(bytes, 'extra.xlsx'), { settings: DEFAULT_SETTINGS });

    expect(loaded.shipment.source.unknownHeaders).toContain('BrokerReference');
    expect(statusOf(loaded, 'columns')).toBe('warn');
    const issue = validateShipment(loaded.shipment).issues.find((item) => item.field === 'unmappedColumns');
    expect(issue?.message).toContain('BrokerReference');
  });

  it('reports rather than blocks: a failing sheet still has fillable fields', () => {
    const loaded = damaged((row) => (row[2] = ''));
    const result = buildPreflight(loaded.shipment, loaded.validation, loaded.notes);
    expect(result.ready).toBe(false);

    document.body.innerHTML = html('ace-commodities');
    const report = fillFields(
      { shipment: loaded.shipment, page: 'commodities', scope: 'commodityLine', line: 1, settings: DEFAULT_SETTINGS },
      document,
    );
    // The good fields are typed; the missing Schedule B is left alone, never
    // guessed and never partially written.
    expect(report.filled).toBeGreaterThan(0);
    expect((document.getElementById('scheduleBNumber') as HTMLInputElement).value).toBe('');
    expect((document.getElementById('commodityLines[0].goodsValue.stringField') as HTMLInputElement).value).toBe('651218');
  });
});

beforeEach(() => {
  document.body.innerHTML = '';
});
