/**
 * Canonical shipment -> ACE_Import.xlsx.
 *
 * The output is the Phase 1 import template, not a new format: the same
 * columns, in the same order, with shipment-level values on the first row -
 * exactly what `src/excel/canonicalMapper.ts` expects. A round-trip test reads
 * a generated workbook back through the extension's own reader and asserts the
 * canonical model comes out unchanged, so "the extension can open this" is a
 * checked claim rather than an intention.
 *
 * Two extra sheets are written for the human, and ignored by the importer
 * because it only reads the first sheet:
 *   Audit  - every field, where it came from, and what it looked like before.
 *   Checks - the validation result at the moment of export.
 */

import * as XLSX from 'xlsx';
import { TEMPLATE_COLUMNS } from '../../../src/excel/columnAliases.js';
import type { CanonicalShipment } from '../../../src/models/CanonicalInvoice.js';
import { parseNumeric } from '../../../src/ace/transformers/numbers.js';
import { detectWeightUnit } from '../../../src/ace/transformers/weight.js';
import type { ValidationResult } from '../../../src/excel/validator.js';
import type { OriginIndex } from '../mapping/types.js';

export interface WorkbookOptions {
  /** 'kg' writes the converted weight; 'lb' writes the QuickBooks pounds. */
  weightUom: 'kg' | 'lb';
  includeAuditSheet: boolean;
  validation?: ValidationResult;
  /** Free-text line recorded on the Audit sheet, e.g. the qbXML version used. */
  generatedBy?: string;
}

type Cell = string | number;

/**
 * The weight to write, and the unit to declare beside it.
 *
 * When the caller asked for pounds, the *original* pounds are recovered from
 * provenance rather than converting the kilograms back: 176,000 lb -> 79,832 kg
 * -> 175,998 lb would lose pounds to rounding, and an audit trail that does not
 * round-trip is worse than no audit trail.
 */
function weightCells(
  shipment: CanonicalShipment,
  line: number,
  kg: number | null,
  weightUom: 'kg' | 'lb',
): { value: Cell; unit: string } {
  if (kg === null) return { value: '', unit: '' };
  if (weightUom === 'kg') return { value: kg, unit: 'kg' };

  const original = shipment.provenance.commodities[line]?.['shippingWeight']?.original ?? '';
  const parsed = parseNumeric(original);
  if (parsed.ok && parsed.value !== null && detectWeightUnit(parsed.unit) === 'lb') {
    return { value: parsed.value, unit: 'lb' };
  }
  // Nothing in pounds to recover: kilograms are what we actually know.
  return { value: kg, unit: 'kg' };
}

export function buildShipmentRows(shipment: CanonicalShipment, options: WorkbookOptions): Cell[][] {
  const { invoice, commodities } = shipment;
  const rows: Cell[][] = [TEMPLATE_COLUMNS as Cell[]];

  commodities.forEach((commodity, index) => {
    const first = index === 0;
    const weight = weightCells(shipment, commodity.line, commodity.shippingWeight, options.weightUom);
    // Shipment-level columns are written once, on the first line. The importer
    // takes the first value it sees and warns when later rows disagree, so
    // repeating them would only create noise.
    const header = (value: string): Cell => (first ? value : '');

    rows.push([
      commodity.line,
      commodity.exportInformationCode,
      commodity.scheduleB,
      commodity.description,
      commodity.quantity1 ?? '',
      commodity.uom1,
      commodity.quantity2 ?? '',
      commodity.uom2,
      commodity.origin,
      commodity.valueOfGoods ?? '',
      weight.value,
      weight.unit,
      commodity.eccn,
      commodity.licenseCode,
      header(invoice.customerName),
      header(invoice.invoiceNumber),
      header(invoice.invoiceDate),
      header(invoice.billTo),
      header(invoice.billToAddress2),
      header(invoice.billToCity),
      header(invoice.billToState),
      header(invoice.billToPostalCode),
      header(invoice.billToCountry),
      header(invoice.originState),
      header(invoice.freightTerms),
      header(invoice.paymentTerms),
      header(invoice.paymentDueDate),
      header(invoice.poNumber),
      header(invoice.carrier),
      header(invoice.vessel),
      header(invoice.bookingNumber),
      header(invoice.containerNumber),
      header(invoice.sealNumber),
      header(invoice.destination),
    ]);
  });

  return rows;
}

function auditRows(shipment: CanonicalShipment, origins: OriginIndex, options: WorkbookOptions): Cell[][] {
  const rows: Cell[][] = [
    ['ACE Helper - QuickBooks export audit', ''],
    ['Source', shipment.source.fileName],
    ['Exported', shipment.source.importedAt],
    ...(options.generatedBy ? [['Generated by', options.generatedBy] as Cell[]] : []),
    ['', ''],
    ['Scope', 'Line', 'Field', 'Origin', 'QuickBooks source', 'Original', 'Transformation', 'Value written'],
  ];

  for (const [field, source] of Object.entries(origins.invoice)) {
    const record = shipment.provenance.invoice[field];
    rows.push([
      'Invoice',
      '',
      field,
      source.origin,
      source.source,
      record?.original ?? '',
      record?.transform ?? '',
      record?.normalized ?? '',
    ]);
  }

  for (const commodity of shipment.commodities) {
    const lineOrigins = origins.commodities[commodity.line] ?? {};
    const lineProvenance = shipment.provenance.commodities[commodity.line] ?? {};
    for (const [field, source] of Object.entries(lineOrigins)) {
      const record = lineProvenance[field];
      rows.push([
        'Commodity',
        commodity.line,
        field,
        source.origin,
        source.source,
        record?.original ?? '',
        record?.transform ?? '',
        record?.normalized ?? '',
      ]);
    }
  }

  return rows;
}

export function checkRows(validation: ValidationResult): Cell[][] {
  const rows: Cell[][] = [
    ['Validation at the moment of export', ''],
    ['Errors', validation.errors],
    ['Warnings', validation.warnings],
    ['', ''],
    ['Severity', 'Scope', 'Line', 'Field', 'Message'],
  ];
  for (const issue of validation.issues) {
    rows.push([issue.severity, issue.scope, issue.line ?? '', issue.label, issue.message]);
  }
  if (!validation.issues.length) rows.push(['ok', '', '', '', 'No errors and no warnings.']);
  return rows;
}

export function widthsFor(rows: Array<Array<string | number>>, max = 40): XLSX.ColInfo[] {
  const widths: number[] = [];
  for (const row of rows) {
    row.forEach((cell, index) => {
      const length = String(cell ?? '').length;
      widths[index] = Math.max(widths[index] ?? 10, Math.min(length + 2, max));
    });
  }
  return widths.map((wch) => ({ wch }));
}

/** Build the workbook. Returns the .xlsx bytes; nothing is written to disk here. */
export function buildAceWorkbook(
  shipment: CanonicalShipment,
  origins: OriginIndex,
  options: WorkbookOptions,
): Uint8Array {
  const workbook = XLSX.utils.book_new();

  const shipmentRows = buildShipmentRows(shipment, options);
  const shipmentSheet = XLSX.utils.aoa_to_sheet(shipmentRows);
  shipmentSheet['!cols'] = widthsFor(shipmentRows, 34);
  shipmentSheet['!freeze'] = { xSplit: 0, ySplit: 1 };
  // First sheet, because the importer reads the first sheet by default.
  XLSX.utils.book_append_sheet(workbook, shipmentSheet, 'Shipment');

  if (options.includeAuditSheet) {
    const rows = auditRows(shipment, origins, options);
    const sheet = XLSX.utils.aoa_to_sheet(rows);
    sheet['!cols'] = widthsFor(rows, 60);
    XLSX.utils.book_append_sheet(workbook, sheet, 'Audit');

    if (options.validation) {
      const rowsForChecks = checkRows(options.validation);
      const checks = XLSX.utils.aoa_to_sheet(rowsForChecks);
      checks['!cols'] = widthsFor(rowsForChecks, 90);
      XLSX.utils.book_append_sheet(workbook, checks, 'Checks');
    }
  }

  const buffer = XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' }) as Buffer;
  return new Uint8Array(buffer);
}

/** Characters Windows will not accept in a file name, plus the C0 controls. */
const UNSAFE_FILENAME_CHARS = new RegExp('[\\u0000-\\u001f<>:"/\\\\|?*]', 'g');

/** Strip everything a Windows path will not accept, and keep it short. */
export function sanitizeFileNamePart(value: string): string {
  // Trim the leading/trailing dots and spaces before collapsing whitespace, or
  // " ..name.. " keeps them as hyphens. Windows also rejects a trailing dot.
  const cleaned = value
    .replace(UNSAFE_FILENAME_CHARS, '')
    .replace(/^[.\s]+|[.\s]+$/g, '')
    .replace(/\s+/g, '-');
  return cleaned.slice(0, 60).replace(/[.\s]+$/, '');
}

export interface FileNameTokens {
  refNumber: string;
  txnId: string;
  date: string;
  customer: string;
}

/** Expand `ACE_Invoice_{refNumber}.xlsx` against one invoice. */
export function aceFileName(pattern: string, tokens: FileNameTokens): string {
  const table: Record<string, string> = {
    refNumber: tokens.refNumber,
    txnId: tokens.txnId,
    date: tokens.date,
    customer: tokens.customer,
  };
  const expanded = pattern.replace(/\{(\w+)\}/g, (whole, key: string) => {
    const value = table[key];
    if (value === undefined) return whole;
    return sanitizeFileNamePart(value);
  });
  const name = expanded.replace(/[{}]/g, '');
  return name.toLowerCase().endsWith('.xlsx') ? name : `${name}.xlsx`;
}
