/**
 * The bill calculation, as a workbook a person can check.
 *
 * Three sheets:
 *   Invoice  - the invoice as QuickBooks returned it: lines and totals.
 *   Bill     - the bill that was (or would be) written, with the commission
 *              arithmetic as LIVE formulas, so a reviewer can see, not just
 *              read, that -ROUND(subtotal x rate, 2) is what was posted, and
 *              a tie-out row that says whether the goods equal the invoice.
 *   Checks   - the duplicate / vendor / account checks, when they ran.
 *
 * Every formula cell also carries the value the companion computed, so the
 * file reads correctly in a viewer that does not recalculate, and a test can
 * assert the cached number equals the plan's.
 */

import * as XLSX from 'xlsx';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { isAbsolute, join, resolve } from 'node:path';
import type { BillChecks, BillWriteResult } from '../adapter/BillWriter.js';
import { ratePercent, type BillPlan } from '../bill/billPlan.js';
import type { QbInvoice } from '../qbxml/types.js';
import type { ExportResult } from '../adapter/InvoiceSourceAdapter.js';
import { aceFileName, widthsFor } from './aceWorkbook.js';
import { ExportError } from './exportAce.js';

export interface BillOutcome {
  checks: BillChecks | null;
  written: BillWriteResult | null;
}

export interface BillWorkbookOptions {
  /** Free-text line recorded on the Bill sheet, e.g. the source label. */
  generatedBy?: string;
}

type Cell = string | number | XLSX.CellObject;

const MONEY = '#,##0.00;-#,##0.00';

function money(value: number, formula?: string): XLSX.CellObject {
  return { t: 'n', v: value, z: MONEY, ...(formula ? { f: formula } : {}) };
}

function invoiceRows(invoice: QbInvoice): Cell[][] {
  const rows: Cell[][] = [
    ['Invoice', invoice.refNumber],
    ['TxnID', invoice.txnId],
    ['Date', invoice.txnDate],
    ['Customer', invoice.customer.fullName],
    ['Terms', invoice.terms.fullName],
    ['Due', invoice.dueDate],
    ['PO number', invoice.poNumber],
    [],
    ['#', 'Item', 'Description', 'Quantity', 'Unit', 'Rate', 'Amount'],
  ];
  invoice.lines.forEach((line, index) => {
    rows.push([
      index + 1,
      line.item.fullName,
      line.desc,
      line.quantity ?? '',
      line.unitOfMeasure,
      line.rate ?? '',
      line.amount === null ? '' : money(line.amount),
    ]);
  });
  rows.push([]);
  rows.push(['', '', '', '', '', 'Invoice subtotal', invoice.subtotal === null ? '' : money(invoice.subtotal)]);
  rows.push(['', '', '', '', '', 'Invoice total', invoice.totalAmount === null ? '' : money(invoice.totalAmount)]);
  return rows;
}

/** Row and column bookkeeping for the Bill sheet, 1-based as Excel counts. */
interface BillLayout {
  rows: Cell[][];
  goodsSubtotalRow: number;
  commissionRow: number | null;
  totalRow: number;
}

function billRows(plan: BillPlan, outcome: BillOutcome, invoice: QbInvoice, options: BillWorkbookOptions): BillLayout {
  const status = outcome.written
    ? `written to QuickBooks: TxnID ${outcome.written.txnId}`
    : outcome.checks
      ? outcome.checks.ok
        ? 'preview only: checks passed, nothing written'
        : 'preview only: a check failed, nothing written'
      : 'preview only: nothing written';

  const rows: Cell[][] = [
    ['Bill', plan.refNumber],
    ['Status', status],
    ['Vendor', plan.vendor, plan.vendorSource],
    ['Date', plan.txnDate, 'invoice date'],
    ['Due', plan.dueDate || '(from terms)', plan.dueDate ? 'invoice due date' : 'QuickBooks derives it'],
    ['Terms', plan.terms, 'invoice terms'],
    ['Ref number', plan.refNumber, 'invoice number'],
    ['Customer', plan.customerName, plan.customerShortName !== plan.customerName ? `short name: ${plan.customerShortName}` : ''],
    ['Memo', plan.memo],
    ['From invoice', invoice.refNumber, `TxnID ${invoice.txnId}`],
    ...(options.generatedBy ? [['Generated by', options.generatedBy] as Cell[]] : []),
    [],
    ['#', 'Account', 'Memo', 'Amount', 'Rule'],
  ];
  const firstLineRow = rows.length + 1;
  for (const line of plan.lines) {
    rows.push([line.line, line.account, line.memo, money(line.amount), line.accountSource]);
  }
  const lastLineRow = rows.length;

  rows.push([]);
  const goodsSubtotalRow = rows.length + 1;
  rows.push(['', 'Goods subtotal', '', money(plan.goodsSubtotal, `SUM(D${firstLineRow}:D${lastLineRow})`)]);

  let commissionRow: number | null = null;
  if (plan.commission) {
    const rateRow = rows.length + 1;
    rows.push(['', 'Commission rate', '', { t: 'n', v: plan.commission.rate, z: '0.00%' }, plan.commission.source]);
    commissionRow = rows.length + 1;
    rows.push([
      'C',
      plan.commission.account,
      plan.commission.memo,
      money(plan.commission.amount, `-ROUND(D${goodsSubtotalRow}*D${rateRow},2)`),
      `${ratePercent(plan.commission.rate)}% of the goods subtotal, rounded to the cent, posted negative`,
    ]);
  }

  const totalRow = rows.length + 1;
  rows.push([
    '',
    'Bill total',
    '',
    money(plan.total, commissionRow ? `D${goodsSubtotalRow}+D${commissionRow}` : `D${goodsSubtotalRow}`),
  ]);

  rows.push([]);
  const invoiceSubtotal = invoice.subtotal ?? invoice.totalAmount;
  if (invoiceSubtotal !== null) {
    const subtotalRow = rows.length + 1;
    rows.push(['', 'Invoice subtotal', '', money(invoiceSubtotal), 'from the Invoice sheet']);
    rows.push([
      '',
      'Check: goods = invoice subtotal',
      '',
      {
        t: 's',
        v: Math.abs(plan.goodsSubtotal - invoiceSubtotal) < 0.005 ? 'OK' : 'DIFFERS',
        f: `IF(ABS(D${goodsSubtotalRow}-D${subtotalRow})<0.005,"OK","DIFFERS")`,
      },
    ]);
  }

  for (const item of plan.skipped) rows.push(['', `Line ${item.line} skipped`, item.reason]);
  for (const warning of plan.warnings) rows.push(['', 'Note', warning]);

  return { rows, goodsSubtotalRow, commissionRow, totalRow };
}

function checkRows(checks: BillChecks): Cell[][] {
  const rows: Cell[][] = [['Result', 'Check', 'Detail']];
  for (const item of checks.items) rows.push([item.ok ? 'ok' : 'FAILED', item.label, item.detail]);
  return rows;
}

function widths(rows: Cell[][], max: number): XLSX.ColInfo[] {
  return widthsFor(
    rows.map((row) => row.map((cell) => (typeof cell === 'object' ? String(cell.v ?? '') : cell))),
    max,
  );
}

/** Build the workbook. Returns the .xlsx bytes; nothing is written to disk here. */
export function buildBillWorkbook(plan: BillPlan, invoice: QbInvoice, outcome: BillOutcome, options: BillWorkbookOptions = {}): Uint8Array {
  const workbook = XLSX.utils.book_new();

  const bill = billRows(plan, outcome, invoice, options);
  const billSheet = XLSX.utils.aoa_to_sheet(bill.rows);
  billSheet['!cols'] = widths(bill.rows, 70);
  XLSX.utils.book_append_sheet(workbook, billSheet, 'Bill');

  const invoiceCells = invoiceRows(invoice);
  const invoiceSheet = XLSX.utils.aoa_to_sheet(invoiceCells);
  invoiceSheet['!cols'] = widths(invoiceCells, 60);
  XLSX.utils.book_append_sheet(workbook, invoiceSheet, 'Invoice');

  if (outcome.checks) {
    const checkCells = checkRows(outcome.checks);
    const checkSheet = XLSX.utils.aoa_to_sheet(checkCells);
    checkSheet['!cols'] = widths(checkCells, 90);
    XLSX.utils.book_append_sheet(workbook, checkSheet, 'Checks');
  }

  const buffer = XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' }) as Buffer;
  return new Uint8Array(buffer);
}

export interface WriteBillWorkbookOptions extends BillWorkbookOptions {
  directory: string;
  /** Either a literal file name, or a pattern containing {refNumber} etc. */
  fileNameOrPattern: string;
  failIfExists?: boolean;
}

export function writeBillWorkbook(plan: BillPlan, invoice: QbInvoice, outcome: BillOutcome, options: WriteBillWorkbookOptions): ExportResult {
  const fileName = aceFileName(options.fileNameOrPattern, {
    refNumber: plan.refNumber,
    txnId: plan.invoiceTxnId,
    date: plan.txnDate,
    customer: plan.customerName,
  });
  const directory = isAbsolute(options.directory) ? options.directory : resolve(process.cwd(), options.directory);
  mkdirSync(directory, { recursive: true });

  const path = join(directory, fileName);
  if (options.failIfExists !== false && existsSync(path)) {
    throw new ExportError(`"${path}" already exists. Move it, or pass --force to replace it.`);
  }
  const bytes = buildBillWorkbook(plan, invoice, outcome, options.generatedBy ? { generatedBy: options.generatedBy } : {});
  writeFileSync(path, bytes);
  return { path, fileName, bytes: bytes.byteLength };
}
