/**
 * A workbook written by the QuickBooks companion (`ace-export`).
 *
 * The companion deliberately writes the Phase 1 import template, so this
 * source parses it through *exactly* the same reader, mapper and validator as
 * ExcelSource. It differs in one respect only: it recognises the companion's
 * Audit sheet and reads the provenance line off it, so the panel can say
 * "QuickBooks Desktop, exported 2026-09-21" instead of "a spreadsheet".
 *
 * That distinction matters because an ACE filing is a legal declaration and
 * "the accounting system said so" and "somebody typed it" should not look
 * alike. It must never change the numbers - and a test asserts that loading
 * the same workbook through ExcelSource produces an identical canonical model.
 */

import { mapSheetToCanonical } from '../excel/canonicalMapper.js';
import { sheetByName, type RawSheet, type RawWorkbook } from '../excel/excelReader.js';
import { validateShipment } from '../excel/validator.js';
import type {
  SourceDescriptor,
  SourceLoadOptions,
  SourceLoadResult,
  WorkbookDataSource,
} from './InvoiceDataSource.js';

/** The Audit sheet's first cell, written by companion/src/excel/aceWorkbook.ts. */
const AUDIT_BANNER = 'ACE Helper - QuickBooks export audit';
const AUDIT_SHEET = 'Audit';

function cellText(sheet: RawSheet, row: number, column: number): string {
  const value = sheet.rows[row]?.[column];
  if (value === null || value === undefined) return '';
  return value instanceof Date ? value.toISOString().slice(0, 10) : String(value).trim();
}

/** Read one "Label | value" pair out of the Audit sheet's header block. */
function auditValue(sheet: RawSheet, label: string): string {
  for (let row = 0; row < Math.min(sheet.rows.length, 12); row += 1) {
    if (cellText(sheet, row, 0).toLowerCase() === label.toLowerCase()) return cellText(sheet, row, 1);
  }
  return '';
}

function auditSheet(workbook: RawWorkbook): RawSheet | null {
  const sheet = workbook.sheets.find((candidate) => candidate.name === AUDIT_SHEET);
  if (!sheet) return null;
  return cellText(sheet, 0, 0) === AUDIT_BANNER ? sheet : null;
}

export class QuickBooksExportSource implements WorkbookDataSource {
  readonly id = 'quickbooks-export' as const;
  readonly label = 'QuickBooks export';
  readonly available = true;

  /** 2 beats ExcelSource's 1, but only when the companion's banner is present. */
  accepts(workbook: RawWorkbook): number {
    return auditSheet(workbook) ? 2 : 0;
  }

  describe(workbook: RawWorkbook): SourceDescriptor {
    const sheet = auditSheet(workbook);
    const generatedBy = sheet ? auditValue(sheet, 'Generated by') : '';
    const exported = sheet ? auditValue(sheet, 'Exported') : '';
    const parts = [generatedBy || 'ACE Export Helper', exported ? `exported ${exported.slice(0, 10)}` : ''].filter(
      (part) => part !== '',
    );
    return { id: this.id, label: this.label, detail: parts.join(' - ') };
  }

  load(workbook: RawWorkbook, options: SourceLoadOptions): SourceLoadResult {
    // Same reader, same mapper, same validator as ExcelSource. Only the
    // descriptor differs.
    const sheet = sheetByName(workbook, options.sheetName);
    const { shipment, notes } = mapSheetToCanonical(sheet, {
      fileName: workbook.fileName,
      settings: options.settings,
    });
    const validation = validateShipment(shipment);
    return {
      shipment,
      validation,
      notes,
      source: this.describe(workbook),
      selectedLine: shipment.commodities[0]?.line ?? 1,
    };
  }
}
